name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Directory on Ubuntu Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEV_SERVER_IP }}
        username: ${{ secrets.DEV_SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        debug: true
        script: |
          whoami
          ls -al
          mkdir -p /var/www/onlygames-frontend

    - name: Copy Repository Files
      run: |
        rsync -a --exclude='node_modules/' $GITHUB_WORKSPACE/{docker-compose.yml,package.json,wordpress.Dockerfile,composer.json,composer.lock,wp-app} /var/www/onlygames-frontend
        
    - name: Create .env file
      run: |
        echo "WORDPRESS_PORT=${{ secrets.DEV_WORDPRESS_PORT }}" > /var/www/onlygames-frontend/.env
        echo "MYSQL_PORT=${{ secrets.DEV_MYSQL_PORT }}" >> /var/www/onlygames-frontend/.env
        echo "PHPMYADMIN_PORT=${{ secrets.DEV_PHPMYADMIN_PORT }}" >> /var/www/onlygames-frontend/.env
        echo "WORDPRESS_DB_HOST=${{ secrets.DEV_WORDPRESS_DB_HOST }}" >> /var/www/onlygames-frontend/.env
        echo "WORDPRESS_DB_USER=${{ secrets.DEV_WORDPRESS_DB_USER }}" >> /var/www/onlygames-frontend/.env
        echo "WORDPRESS_DB_PASSWORD=${{ secrets.DEV_WORDPRESS_DB_PASSWORD }}" >> /var/www/onlygames-frontend/.env
        echo "WORDPRESS_DB_NAME=${{ secrets.DEV_WORDPRESS_DB_NAME }}" >> /var/www/onlygames-frontend/.env
        echo "WORDPRESS_DB_ROOT_PASSWORD=${{ secrets.DEV_WORDPRESS_DB_ROOT_PASSWORD }}" >> /var/www/onlygames-frontend/.env
        echo "WORDPRESS_TABLE_PREFIX=${{ secrets.DEV_WORDPRESS_TABLE_PREFIX }}" >> /var/www/onlygames-frontend/.env

    - name: Build and Push Docker Image
      run: |
        echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
        chmod 600 deploy_key
        eval $(ssh-agent -s)
        ssh-add deploy_key
        docker-compose build

    - name: SSH into Ubuntu Server and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SERVER_IP }}
        username: ${{ secrets.DEV_SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/onlygames-frontend
          if ! docker-compose pull; then
            echo "Error pulling Docker images"
            exit 1
          fi

          if ! docker-compose down; then
            echo "Error stopping existing containers"
            exit 1
          fi

          if ! docker-compose up -d; then
            echo "Error starting Docker containers"
            exit 1
          fi
