name: Debug SSH Connection

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'Target branch for deployment'
        required: true

jobs:
  debug_ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Debug SSH Connection
      run: |
        echo "Connecting to the server..."
        echo "DEV_SERVER_IP: ${{ secrets.DEV_SERVER_IP }}"
        echo "DEV_SERVER_USERNAME: ${{ secrets.DEV_SERVER_USERNAME }}"
        echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"
        
        # Setup SSH Key
        echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
        chmod 600 deploy_key
        eval $(ssh-agent -s)
        ssh-add deploy_key

        # Attempt SSH Connection
        ssh -o StrictHostKeyChecking=no -v ${{ secrets.DEV_SERVER_USERNAME }}@${{ secrets.DEV_SERVER_IP }} exit

        # Cleanup SSH Key
        ssh-agent -k
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
